class[0].name = \cm[na1{age}: attribute name]
class[0].type = {youth, adult, senior}
target[0].all = \cm[age{?}: instance class label]

class[1].name = \cm[na2{gender}: attribute name]
class[1].type = {m,f}
target[1].all = \cm[gender{?}: instance class label]

class[2].name = \cm[na3{ewe}: attribute name]
class[2].type = \cm[cl3{numeric}: all classes for arff file attribute]
target[2].all = \cm[ewe{?}: instance class label]

class[3].name = \cm[na4{likeability}: attribute name]
class[3].type = {L,NL}
target[3].all = \cm[likeability{?}: instance class label]
